# --- Stage 1: Build Stage ---
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod ./
RUN go.mod download
COPY . .
# Compile the main application binary smoothly
RUN CGO_ENABLED=0 GOOS=linux go build -o main main.go

# --- Stage 2: Minimal Runtime Environment ---
FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /root/

# Copy binary + relative web directories into deployment container root
COPY --from=builder /app/main .
COPY --from=builder /app/templates ./templates
COPY --from=builder /app/static ./static

CMD ["./main"]
